EndPoint.WebUI/Areas/Admin/Controllers/ProductCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using RS.Contracts.ProductCategories;

namespace EndPoint.WebUI.Areas.Admin.Controllers;
[Area("Admin")]
public class ProductCategoryController : Controller
{
    public ProductCategorySearchModel SearchModel;
    public List<ProductCategoryViewModel> ProductCategories;
    private readonly IProductCategoryApplication _productCategoryApplication;

    public ProductCategoryController(IProductCategoryApplication productCategoryApplication)
    {
        _productCategoryApplication = productCategoryApplication;
    }
    //[NeedsPermission(ShopPermissions.ListProductCategories)]

    public IActionResult Index(string searchString)
    {
        ProductCategories = _productCategoryApplication.Search(searchString);
        return View("Index", ProductCategories);
    }

    [HttpGet]
    public PartialViewResult Create()
    {
        return PartialView("Create", new CreateProductCategory());
    }
    [HttpPost]
    //[NeedsPermission(ShopPermissions.CreateProductCategory)]
    public JsonResult Create(CreateProductCategory command)
    {
        var result = _productCategoryApplication.Create(command);
        return new JsonResult(result);
    }

    public PartialViewResult Edit(long id)
    {
        var productCategory = _productCategoryApplication.GetDetails(id);
        return PartialView("Edit", productCategory);
    }
    [HttpPost]
    //[NeedsPermission(ShopPermissions.EditProductCategory)]
    public IActionResult Edit(EditProductCategory command)
    {
        if (!ModelState.IsValid)
        {
            return new JsonResult(new { message = "فایل انتخاب شده مجاز نیست" });
        }

        var result = _productCategoryApplication.Edit(command);
        return new JsonResult(result);
    }
}

EndPoint.WebUI/Areas/Admin/Views/ProductCategory/Create.cshtml
@model RS.Contracts.ProductCategories.CreateProductCategory

@{
    ViewData["Title"] = "Create";
}
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">افزودن دسته بندی املاک</h4>
    </div>

    <form asp-controller="ProductCategory" asp-action="Create"
          method="post"
          data-ajax="true"
          data-callback=""
          data-action="Refresh"
          enctype="multipart/form-data">
        <div class="modal-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label">نام</label>
                        <input type="text" class="form-control"
                               asp-for="Name" onchange="makeSlug('Name', 'Slug')">
                        <span asp-validation-for="Name" class="error"></span>
                    </div>
                </div><div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Slug" class="control-label">اسلاگ</label>
                        <input type="text" class="form-control" asp-for="Slug">
                        <span asp-validation-for="Slug" class="error"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="Picture" class="control-label">عکس</label>
                        <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                        <span asp-validation-for="Picture" class="error"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="PictureAlt" class="control-label">Alt</label>
                        <input type="text" class="form-control" asp-for="PictureAlt">
                        <span asp-validation-for="PictureAlt" class="error"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="PictureTitle" class="control-label">عنوان</label>
                        <input type="text" class="form-control" asp-for="PictureTitle">
                        <span asp-validation-for="PictureTitle" class="error"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group no-margin">
                        <label asp-for="Description" class="control-label">توضیحات</label>
                        <textarea class="form-control autogrow" asp-for="Description" onchange="fillField('Description', 'MetaDescription')"
                                  style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                        <span asp-validation-for="Description" class="error"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="Keywords" class="control-label">کلمات کلیدی</label>
                        <input type="text" class="form-control" asp-for="Keywords">
                        <span asp-validation-for="Keywords" class="error"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group no-margin">
                        <label asp-for="MetaDescription" class="control-label">توضیحات متا</label>
                        <textarea class="form-control autogrow" asp-for="MetaDescription"
                                  style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                        <span asp-validation-for="MetaDescription" class="error"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
            <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
        </div>
    </form>
</div>

EndPoint.WebUI/Areas/Admin/Views/ProductCategory/Edit.cshtml
@using RS.Contracts.ProductCategories
@model EditProductCategory

@{
    ViewData["Title"] = "Edit";
}

<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">ویرایش دسته :‌@Model.Name</h4>
    </div>

    <form asp-controller="ProductCategory" asp-action="Edit"
            method="post"
            data-ajax="true"
            data-callback=""
            data-action="Refresh"
            enctype="multipart/form-data">
        <div class="modal-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label">نام</label>
                        <input type="text" class="form-control" asp-for="Name">
                        <span asp-validation-for="Name" class="error"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Slug" class="control-label">اسلاگ</label>
                        <input type="text" class="form-control" asp-for="Slug">
                        <span asp-validation-for="Slug" class="error"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="Picture" class="control-label">عکس</label>
                        <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                        <span asp-validation-for="Picture" class="error"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="PictureAlt" class="control-label">Alt</label>
                        <input type="text" class="form-control" asp-for="PictureAlt">
                        <span asp-validation-for="PictureAlt" class="error"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="PictureTitle" class="control-label">عنوان</label>
                        <input type="text" class="form-control" asp-for="PictureTitle">
                        <span asp-validation-for="PictureTitle" class="error"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group no-margin">
                        <label asp-for="Description" class="control-label">توضیحات</label>
                        <textarea class="form-control autogrow" asp-for="Description" onchange="fillField('Description', 'MetaDescription')"
                                    style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                        <span asp-validation-for="Description" class="error"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="Keywords" class="control-label">کلمات کلیدی</label>
                        <input type="text" class="form-control" asp-for="Keywords">
                        <span asp-validation-for="Keywords" class="error"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group no-margin">
                        <label asp-for="MetaDescription" class="control-label">توضیحات متا</label>
                        <textarea class="form-control autogrow" asp-for="MetaDescription"
                                    style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                        <span asp-validation-for="MetaDescription" class="error"></span>
                    </div>
                </div>
            </div>
            <input type="hidden" asp-for="Id" value="@Model.Id" />
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
            <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
        </div>
    </form>
</div>      

EndPoint.WebUI/Areas/Admin/Views/ProductCategory/Index.cshtml
@using RS.Contracts.ProductCategories;
@model List<ProductCategoryViewModel>

@{
    ViewData["Title"] = "دسته بندی املاک";
}
<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["Title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Action("Create")">افزودن دسته املاک </a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجوی دسته ها</h3>
            </div>
            <div class="panel-body">
                <form asp-controller="ProductCategory" asp-action="Index"
                      class="form-inline" role="form" method="get">
                    <div class="form-group">
                        
                        <input class="form-control" type="text" name="searchString" placeholder="نوع ملک" />
                        <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                        <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="/Index">مشاهده همه</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">دسته بندی املاک</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>عکس</th>
                                    <th>نام</th>
                                    <th>تاریخ ایجاد</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>
                                            <img src="~/Images/@item.Picture" 
                                             class="rounded-circle" width="70" height="70"
                                             asp-append-version="true" />
                                        </td>
                                        <td>@item.Name</td>
                                        <td>@item.CreationDate</td>
                                        <td>
                                            <a class="btn btn-warning pull-right m-rl-5"                                         
                                            href="#showmodal=@Url.Action("Edit", new { id = item.Id})">
                                            <i class="fa fa-edit"></i>ویرایش</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/AdminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/AdminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}