EndPoint.WebUI/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RS.Contracts.ProductCategories;
using RS.Contracts.Products;

namespace EndPoint.WebUI.Areas.Admin.Controllers;
[Area("Admin")]
public class ProductController : Controller
{
    [TempData]
    public string Message { get; set; }
    public ProductSearchModel SearchModel;
    public List<ProductViewModel> Products;
    public SelectList ProductCategories;


    private readonly IProductApplication _productApplication;
    private readonly IProductCategoryApplication _productCategoryApplication;

    public ProductController(IProductApplication productApplication,
        IProductCategoryApplication productCategoryApplication)
    {
        _productApplication = productApplication;
        _productCategoryApplication = productCategoryApplication;
    }
    //[NeedsPermission(ShopPermissions.ListProducts)]
    public IActionResult Index(ProductSearchModel searchModel)
    {
        ProductCategories = new SelectList(_productCategoryApplication.GetProductCategories(), "Id", "Name");
        ViewBag.ProductCategories = ProductCategories;
        Products = _productApplication.Search(searchModel);
        ViewBag.Products = Products;
        return View("Index");
    }
    [HttpGet]
    public PartialViewResult Create()
    {
        var command = new CreateProduct
        {
            Categories = _productCategoryApplication.GetProductCategories()
        };
        return PartialView("Create", command);
    }
    [HttpPost]
    //[NeedsPermission(ShopPermissions.CreateProduct)]
    public JsonResult Create(CreateProduct command)
    {
        var result = _productApplication.Create(command);
        return new JsonResult(result);
    }
    [HttpGet]
    public PartialViewResult Edit(long id)
    {
        var product = _productApplication.GetDetails(id);
        product.Categories = _productCategoryApplication.GetProductCategories();
        return PartialView("Edit", product);
    }
    [HttpPost]
    //[NeedsPermission(ShopPermissions.EditProduct)]
    public JsonResult Edit(EditProduct command)
    {
        var result = _productApplication.Edit(command);
        return new JsonResult(result);
    }
}

EndPoint.WebUI/Areas/Admin/Controllers/RoleController.cs
using EndPoint.WebUI.Areas.Admin.Models.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EndPoint.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<AppIdentityRole> _roleManager;

        public RoleController(RoleManager<AppIdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            return View(roles);
        }
        #region Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                AppIdentityRole role = new() { Name = model.Name };
                var result = _roleManager.CreateAsync(role).Result;
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError(item.Code, item.Description);
                    }
                }
            }
            return View(model);
        }
        #endregion

        #region Update
        public IActionResult Update(int id)
        {
            var role = _roleManager.FindByIdAsync(id.ToString()).Result;
            if (role != null)
            {
                UpdateRoleViewModel model = new()
                {
                    Id = role.Id,
                    Name = role.Name,
                };
                return View(model);
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Update(int id, UpdateRoleViewModel model)
        {
            var role = _roleManager.FindByIdAsync(id.ToString()).Result;
            if (role != null)
            {
                role.Name = model.Name;
                var result = _roleManager.UpdateAsync(role).Result;
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError(item.Code, item.Description);
                    }
                }
                return View(model);
            }
            return NotFound();
        }
        #endregion

        #region Delete
        public IActionResult Delete(int id)
        {
            var role = _roleManager.FindByIdAsync(id.ToString()).Result;
            if (role != null)
            {
                var result = _roleManager.DeleteAsync(role).Result;
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError(item.Code, item.Description);
                    }
                }
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        #endregion
    }
}

EndPoint.WebUI/Areas/Admin/Controllers/SlideController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RS.Contracts.Slides;

namespace EndPoint.WebUI.Areas.Admin.Controllers;
[Area("Admin")]
[Authorize]
public class SlideController : Controller
{
    [TempData]
    public string Message { get; set; }

    public List<SlideViewModel> Slides;
    private readonly ISlideApplication _slideApplication;

    public SlideController(ISlideApplication slideApplication)
    {
        _slideApplication = slideApplication;
    }

    public IActionResult Index()
    {
        Slides = _slideApplication.GetList();
        return View("Index", Slides);
    }
    [HttpGet]
    public PartialViewResult Create()
    {
        var command = new CreateSlide();
        return PartialView("Create", command);
    }
    [HttpPost]
    public JsonResult Create(CreateSlide command)
    {
        var result = _slideApplication.Create(command);
        return new JsonResult(result);
    }
    [HttpGet]
    public PartialViewResult Edit(long id)
    {
        var slide = _slideApplication.GetDetails(id);
        return PartialView("Edit", slide);
    }
    [HttpPost]
    public JsonResult Edit(EditSlide command)
    {
        var result = _slideApplication.Edit(command);
        return new JsonResult(result);
    }
    public IActionResult Remove(long id)
    {
        var result = _slideApplication.Remove(id);
        if (result.IsSucceeded)
            return RedirectToAction("Index");
        Message = result.Message;
        return RedirectToAction("Index");
    }
    public IActionResult Restore(long id)
    {
        var result = _slideApplication.Restore(id);
        if (result.IsSucceeded)
            return RedirectToAction("Index"); 
        Message = result.Message;
        return RedirectToAction("Index");
    }
}

EndPoint.WebUI/Areas/Admin/Controllers/UserController.cs
using EndPoint.WebUI.Areas.Admin.Models.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace EndPoint.WebUI.Areas.Admin.Controllers;

[Area("Admin")]
public class UserController : Controller
{
    private readonly UserManager<AppUser> _userManager;

    public UserController(UserManager<AppUser> userManager)
    {
        _userManager = userManager;
    }

    public IActionResult Index()
    {
        var users = _userManager.Users.Take(50).ToList();
        return View(users);
    }
    [HttpGet]
    public PartialViewResult Create()
    {
        return PartialView("Create");
    }
    [HttpPost]
    public JsonResult Create(CreateUserViewModel model)
    {
        if (ModelState.IsValid)
        {
            AppUser user = new()
            {
                UserName = model.UserName,
                FirstName = model.FirstName,
                LastName = model.LastName,
                Email = model.Email,
                BirthDate = model.BirthDate,
            };
            var result = _userManager.CreateAsync(user, model.Password).Result;
            if (result.Succeeded)
            {
                return Json(result);
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.Code, item.Description);
                }
            }
        }
        return new JsonResult(model);
    }
    [HttpGet]
    public PartialViewResult Update(int id)
    {
        var user = _userManager.FindByIdAsync(id.ToString()).Result;
        if (user != null)
        {
            UpdateUserViewModel model = new()
            {
                Id = user.Id,
                UserName = user.UserName,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                BirthDate = user.BirthDate
            };
            return PartialView("Update", model);
        }
        return PartialView("Error");
    }
    [HttpPost]
    public IActionResult Update(int id, UpdateUserViewModel model)
    {
        var user = _userManager.FindByIdAsync(id.ToString()).Result;
        if (user != null)
        {
            user.UserName = model.UserName;
            user.FirstName = model.FirstName;
            user.LastName = model.LastName;
            user.Email = model.Email;
            user.BirthDate = model.BirthDate;

            var result = _userManager.UpdateAsync(user).Result;
            if (result.Succeeded)
            {
                return Json(result);
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.Code, item.Description);
                }
            }
            return new JsonResult(model);
        }
        return NotFound("Index");
    }
    public IActionResult Delete(int id)
    {
        var user = _userManager.FindByIdAsync(id.ToString()).Result;
        if (user != null)
        {
            var result = _userManager.DeleteAsync(user).Result;
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.Code, item.Description);
                }
            }
        }
        return View();
    }
}

EndPoint.WebUI/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Coderthemes">

    <link rel="shortcut icon" href="images/favicon_1.ico">

    <title>@ViewData["Title"] - RealState</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />

    <!-- Base Css Files -->
    <link href="~/AdminTheme/assets/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Font Icons -->
    <link href="~/AdminTheme/assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/AdminTheme/assets/ionicon/css/ionicons.min.css" rel="stylesheet" />
    <link href="~/AdminTheme/assets/css/material-design-iconic-font.min.css" rel="stylesheet">

    <!-- animate css -->
    <link href="~/AdminTheme/assets/css/animate.css" rel="stylesheet" />

    <!-- Waves-effect -->
    <link href="~/AdminTheme/assets/css/waves-effect.css" rel="stylesheet">

    <link href="~/AdminTheme/assets/datatables/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />

    <!-- sweet alerts -->
    <link href="~/AdminTheme/assets/sweet-alert/sweet-alert.min.css" rel="stylesheet">

    <!-- Custom Files -->
    <link href="~/AdminTheme/assets/css/persian-datepicker.css" rel="stylesheet" />

    @RenderSection("Css", false)

    <link href="~/AdminTheme/assets/css/helper.css" rel="stylesheet" type="text/css" />
    <link href="~/AdminTheme/assets/css/style.css" rel="stylesheet" type="text/css" />
    <script src="~/AdminTheme/assets/js/modernizr.min.js"></script>

</head>

<body class="fixed-left">

    <!-- Begin page -->
    <div id="wrapper">

        <!-- Top Bar Start -->
        <div class="topbar">
            <!-- LOGO -->
            <div class="topbar-left">
                <div class="text-center">
                    <a href="index.html" class="logo"><i class="md md-terrain"></i> <span>Moltran </span></a>
                </div>
            </div>
            <!-- Button mobile view to collapse sidebar menu -->
            <div class="navbar navbar-default" role="navigation">
                <div class="container">
                    <div class="">
                        <div class="pull-left">
                            <button class="button-menu-mobile open-left">
                                <i class="fa fa-bars"></i>
                            </button>
                            <span class="clearfix"></span>
                        </div>
                        <form class="navbar-form pull-left" role="search">
                            <div class="form-group">
                                <input type="text" class="form-control search-bar" placeholder="Type here for search...">
                            </div>
                            <button type="submit" class="btn btn-search"><i class="fa fa-search"></i></button>
                        </form>

                        <ul class="nav navbar-nav navbar-right pull-right">
                            <li class="dropdown hidden-xs">
                                <a href="#" data-target="#" class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" aria-expanded="true">
                                    <i class="md md-notifications"></i> <span class="badge badge-xs badge-danger">3</span>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-lg">
                                    <li class="text-center notifi-title">اعلانات</li>
                                    <li class="list-group">
                                        <!-- list item-->
                                        <a href="javascript:void(0);" class="list-group-item">
                                            <div class="media">
                                                <div class="pull-left">
                                                    <em class="fa fa-user-plus fa-2x text-info"></em>
                                                </div>
                                                <div class="media-body clearfix">
                                                    <div class="media-heading">کاربر تازه ای به ما پیوست</div>
                                                    <p class="m-0">
                                                        <small>شما ۱۰ پیام خوانده نشده دارید</small>
                                                    </p>
                                                </div>
                                            </div>
                                        </a>
                                        <!-- list item-->
                                        <a href="javascript:void(0);" class="list-group-item">
                                            <div class="media">
                                                <div class="pull-left">
                                                    <em class="fa fa-diamond fa-2x text-primary"></em>
                                                </div>
                                                <div class="media-body clearfix">
                                                    <div class="media-heading">پیکربندی جدید</div>
                                                    <p class="m-0">
                                                        <small>اینجا پیکربندی های تازه ای در دسترس است</small>
                                                    </p>
                                                </div>
                                            </div>
                                        </a>
                                        <!-- list item-->
                                        <a href="javascript:void(0);" class="list-group-item">
                                            <div class="media">
                                                <div class="pull-left">
                                                    <em class="fa fa-bell-o fa-2x text-danger"></em>
                                                </div>
                                                <div class="media-body clearfix">
                                                    <div class="media-heading">بروزرسانی ها</div>
                                                    <p class="m-0">
                                                        <small>
                                                            اینجا
                                                            <span class="text-primary">2</span>  بروز رسانی تازه موجود است
                                                        </small>
                                                    </p>
                                                </div>
                                            </div>
                                        </a>
                                        <!-- last list item -->
                                        <a href="javascript:void(0);" class="list-group-item">
                                            <small>See all notifications</small>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle profile" data-toggle="dropdown" aria-expanded="true"><img src="~/AdminTheme/assets/images/avatar-1.jpg" alt="user-img" class="img-circle"> </a>
                                <ul class="dropdown-menu">
                                    <li><a href="javascript:void(0)"><i class="md md-face-unlock"></i> Profile</a></li>
                                    <li><a href="javascript:void(0)"><i class="md md-settings"></i> Settings</a></li>
                                    <li><a href="javascript:void(0)"><i class="md md-lock"></i> Lock screen</a></li>
                                    <li><a href="javascript:void(0)"><i class="md md-settings-power"></i> Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <!-- Top Bar End -->

        <partial name="_Menu" />
        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="content-page">
            <!-- Start content -->
            <div class="content">
                <div class="container">

                    @RenderBody()

                </div> <!-- container -->

            </div> <!-- content -->

            <footer class="footer text-right">
                2015 © Moltran.
            </footer>

        </div>
        <!-- ============================================================== -->
        <!-- End Right content here -->
        <!-- ============================================================== -->
    </div>
    <!-- END wrapper -->

    <div id="MainModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content" id="ModalContent">
            </div>
        </div>
    </div>

    <!-- <script> -->
    <!-- var resizefunc = []; -->
    <!-- </script> -->
    <!-- jQuery  -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/AdminTheme/assets/js/bootstrap.min.js"></script>
    <script src="~/AdminTheme/assets/js/waves.js"></script>
    <script src="~/AdminTheme/assets/js/wow.min.js"></script>
    <script src="~/AdminTheme/assets/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="~/AdminTheme/assets/js/jquery.scrollTo.min.js"></script>
    <script src="~/AdminTheme/assets/chat/moment-2.2.1.js"></script>
    <script src="~/AdminTheme/assets/jquery-sparkline/jquery.sparkline.min.js"></script>
    <script src="~/AdminTheme/assets/jquery-detectmobile/detect.js"></script>
    <script src="~/AdminTheme/assets/fastclick/fastclick.js"></script>
    <script src="~/AdminTheme/assets/jquery-slimscroll/jquery.slimscroll.js"></script>
    <script src="~/AdminTheme/assets/jquery-blockui/jquery.blockUI.js"></script>

    <!-- sweet alerts -->
    <script src="~/AdminTheme/assets/sweet-alert/sweet-alert.min.js"></script>
    <script src="~/AdminTheme/assets/sweet-alert/sweet-alert.init.js"></script>

    <!-- flot Chart -->
    <script src="~/AdminTheme/assets/flot-chart/jquery.flot.js"></script>
    <script src="~/AdminTheme/assets/flot-chart/jquery.flot.time.js"></script>
    <script src="~/AdminTheme/assets/flot-chart/jquery.flot.tooltip.min.js"></script>
    <script src="~/AdminTheme/assets/flot-chart/jquery.flot.resize.js"></script>
    <script src="~/AdminTheme/assets/flot-chart/jquery.flot.pie.js"></script>
    <script src="~/AdminTheme/assets/flot-chart/jquery.flot.selection.js"></script>
    <script src="~/AdminTheme/assets/flot-chart/jquery.flot.stack.js"></script>
    <script src="~/AdminTheme/assets/flot-chart/jquery.flot.crosshair.js"></script>

    <!-- Counter-up -->
    <script src="~/AdminTheme/assets/counterup/waypoints.min.js" type="text/javascript"></script>
    <script src="~/AdminTheme/assets/counterup/jquery.counterup.min.js" type="text/javascript"></script>



    <!-- CUSTOM JS -->
    <script src="~/AdminTheme/assets/js/jquery.app.js"></script>

    <!-- Dashboard -->
    <script src="~/AdminTheme/assets/js/jquery.dashboard.js"></script>

    <!-- Chat
    <script src="~/AdminTheme/assets/js/jquery.chat.js"></script>-->
    <!-- Todo -->
    <script src="~/AdminTheme/assets/js/jquery.todo.js"></script>

    <!--Validate-->
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <!--Modal-->
    <script src="~/AdminTheme/assets/js/site.js"></script>

    <script src="~/AdminTheme/assets/js/persian-date.min.js"></script>
    <script src="~/AdminTheme/assets/js/persian-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js" integrity="sha512-ElRFoEQdI5Ht6kZvyzXhYG9NqjtkmlkfYk0wr6wHxU9JEHakS7UJZNeml5ALk+8IKlU6jDgMabC3vkumRokgJA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    @RenderSection("Scripts", false)

    <script>
        $('.persianDateInput').persianDatepicker({
            format: 'YYYY/MM/DD',
            autoClose: true,
            initialValueType: "persian"
        });

    </script>

    <script src="https://cdn.tiny.cloud/1/79zdxz9sjl5osum512i9lwruwinmk80qwpu67slz2sl8gwwk/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>

@*    <script>
        tinymce.init({
            selector: '#BodyContent',
            plugins: 'a11ychecker advcode casechange export formatpainter linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tinycomments tinymcespellchecker',
            toolbar: 'a11ycheck addcomment showcomments casechange checklist code export formatpainter pageembed permanentpen table',
            toolbar_mode: 'floating',
            tinycomments_mode: 'embedded',
            tinycomments_author: 'Author name',
        });
    </script>*@

    <script>
        tinymce.init({
            selector: '#BodyContent',
            plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table | align lineheight | numlist bullist indent outdent | emoticons charmap | removeformat',
        });
    </script>
</body>
</html>

EndPoint.WebUI/Areas/Admin/Views/Shared/_Menu.cshtml
<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <div class="user-details">
            <div class="pull-right">
                <img src="~/AdminTheme/assets/images/users/avatar-1.jpg" alt="" class="thumb-md img-circle">
            </div>
            <div class="user-info">
                <div class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="javascript:void(0)"><i class="md md-face-unlock"></i> Profile<div class="ripple-wrapper"></div></a></li>
                        <li><a href="javascript:void(0)"><i class="md md-settings"></i> Settings</a></li>
                        <li><a href="javascript:void(0)"><i class="md md-lock"></i> Lock screen</a></li>
                        <li>
                            <a asp-area="default" asp-controller="Account" asp-action="Logout">
                            <i class="md md-settings-power"></i> Logout</a>
                        </li>
                    </ul>
                </div>

                <p class="text-muted m-0"></p>
            </div>
        </div>

        <div id="sidebar-menu">
            <ul>
                <li>
                    <a asp-controller="Home" asp-action="Index" class="waves-effect active">
                        <i class="md md-home"></i><span> داشبورد </span></a>
                </li>
                <li>
                    <a asp-Controller="Comment" asp-action="Index" class="waves-effect">
                        <i class="md md-home"></i><span> کامنت ها </span></a>
                </li>
                <li class="has_sub">
                    <a class="waves-effect"><i class="md md-mail"></i><span> فروشگاه </span>
                        <span class="pull-right"><i class="md md-add"></i></span></a>
                    <ul class="list-unstyled">
                        <li><a asp-controller="Slide" asp-Action="Index"> اسلایدر</a></li>
                        <li><a asp-controller="ProductCategory" asp-Action="Index">گروه محصولات</a></li>
                        <li><a asp-controller="Product" asp-action="Index"> محصولات</a></li>
                        <li><a asp-controller="ProductPicture" asp-action="Index">عکس محصولات</a></li>
                    </ul>
                </li>

                <li class="has_sub">
                    <a class="waves-effect"><i class="md md-mail"></i><span>مدیریت کاربران </span>
                        <span class="pull-right"><i class="md md-add"></i></span></a>
                    <ul class="list-unstyled">
                        <li><a asp-controller="User" asp-action="Index">کاربران</a></li>
                        <li><a asp-controller="Role" asp-action="Index">نقش ها</a></li>
                    </ul>
                </li>

                <li class="has_sub">
                    <a class="waves-effect"><i class="md md-mail"></i><span> سیستم بلاگینگ </span>
                        <span class="pull-right"><i class="md md-add"></i></span></a>
                    <ul class="list-unstyled">
                        <li><a asp-controller="Article" asp-action="Index">مقالات</a></li>
                        <li><a asp-controller="Article" asp-action="Index">گروه مقالات</a></li>
                    </ul>
                </li>

                <li>
                    <a asp-area="default" asp-controller="Account" asp-action="Logout" class="waves-effect active">
                        <i class="fa fa-sign-out"></i><span> خروج </span></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>