EndPoint.WebUI/Areas/Admin/Controllers/ProductPictureController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RS.Contracts.ProductPictures;
using RS.Contracts.Products;

namespace EndPoint.WebUI.Areas.Admin.Controllers;
[Area("Admin")]
public class ProductPictureController : Controller
{
    [TempData]
    public string Message { get; set; }
    public ProductPictureSearchModel SearchModel;
    public List<ProductPictureViewModel> ProductPictures;
    public SelectList Products;

    private readonly IProductApplication _productApplication;
    private readonly IProductPictureApplication _productPictureApplication;
    public ProductPictureController(IProductApplication productApplication,
        IProductPictureApplication productPictureApplication)
    {
        _productApplication = productApplication;
        _productPictureApplication = productPictureApplication;
    }

    public IActionResult Index(long productId)
    {
        Products = new SelectList(_productApplication.GetProducts(), "Id", "Name");
        ViewBag.Products = Products;
        ProductPictures = _productPictureApplication.Search(productId);
        //ViewBag.ProductPictures = ProductPictures;

        return View("Index", ProductPictures);
    }
    [HttpGet]
    public PartialViewResult Create()
    {
        var command = new CreateProductPicture
        {
            Products = _productApplication.GetProducts()
        };
        return PartialView("Create", command);
    }
    [HttpPost]
    public JsonResult Create(CreateProductPicture command)
    {
        var result = _productPictureApplication.Create(command);
        return new JsonResult(result);
    }
    [HttpGet]
    public PartialViewResult Edit(long id)
    {
        var productPicture = _productPictureApplication.GetDetails(id);
        productPicture.Products = _productApplication.GetProducts();
        return PartialView("Edit", productPicture);
    }
    [HttpPost]
    public JsonResult Edit(EditProductPicture command)
    {
        var result = _productPictureApplication.Edit(command);
        return new JsonResult(result);
    }

    public IActionResult Remove(long id)
    {
        var result = _productPictureApplication.Remove(id);
        if (result.IsSucceeded)
            return RedirectToAction("Index");
        Message = result.Message;
        return RedirectToAction("Index");

    }
    public IActionResult Restore(long id)
    {
        var result = _productPictureApplication.Restore(id);
        if (result.IsSucceeded)
            return RedirectToAction("Index");

        Message = result.Message;
        return RedirectToAction("Index");
    }
}

EndPoint.WebUI/Areas/Admin/Views/ProductPicture/Create.cshtml
@using RS.Contracts.ProductPictures
@model CreateProductPicture

@{
    ViewData["Title"] = "Create";
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">افزودن تصویر</h4>
</div>

<form asp-controller="ProductPicture" asp-action="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label">ملک</label>
                    <select class="form-control" asp-for="ProductId" asp-items='new SelectList(Model.Products, "Id", "Name")'>
                        <option value="">ملک</option>
                    </select>
                    <span asp-validation-for="ProductId" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">تصویر</label>
                    <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                    <span asp-validation-for="Picture" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureAlt" class="control-label">Alt</label>
                    <input type="text" class="form-control" asp-for="PictureAlt">
                    <span asp-validation-for="PictureAlt" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

EndPoint.WebUI/Areas/Admin/Views/ProductPicture/Edit.cshtml
@using RS.Contracts.ProductPictures
@model EditProductPicture

@{
    ViewData["Title"] = "Edit";
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش تصویر ملک: @Model.PictureAlt</h4>
</div>

<form asp-controller="ProductPicture" asp-action="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label">ملک</label>
                    <select class="form-control" asp-for="ProductId" asp-items='new SelectList(Model.Products, "Id", "Name")'>
                        <option value="">ملک</option>
                    </select>
                    <span asp-validation-for="ProductId" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">عکس</label>
                    <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                    <span asp-validation-for="Picture" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureAlt" class="control-label">Alt</label>
                    <input type="text" class="form-control" asp-for="PictureAlt">
                    <span asp-validation-for="PictureAlt" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
        </div>
        <input type="hidden" asp-form="Id" value="@Model.Id" />
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

EndPoint.WebUI/Areas/Admin/Views/ProductPicture/Index.cshtml
@using RS.Contracts.ProductPictures;
@model List<ProductPictureViewModel>

@{
    ViewData["Title"] = "مدیریت تصویر املاک";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["Title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Action("Create")">افزودن تصویر جدید</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در تصویر املاک</h3>
            </div>
            <div class="panel-body">
                <form asp-controller="ProductPicture" asp-action="Index"
                class="form-inline" role="form" method="get">
                    <div class="form-group">
                  <label class="sr-only" ></label>
                        <select class="form-control" name="productId" asp-items="ViewBag.Products">
                            <option value="0">ملک</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="/Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست تصاویر املاک</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>عکس</th>
                                    <th>نام محصول</th>
                                    <th>وضعیت</th>
                                    <th>تاریخ تولید</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>
                                            <img src="~/Images/@item.Picture" style="width: 70px; height: 70px" />
                                        </td>
                                        <td>@item.Product</td>
                                        <td class="text-center">
                                            @if (!item.IsRemoved)
                                            {
                                                <i class="fa fa-2x fa-check text-success"></i>
                                            }
                                            else
                                            {
                                                <i class="fa fa-2x fa-remove text-danger"></i>
                                            }
                                        </td>
                                        <td>@item.CreationDate</td>
                                        <td>
                                            <a class="btn btn-warning waves-effect waves-light m-b-5"
                                           href="#showmodal=@Url.Action("Edit", new { id = item.Id})">
                                                <i class="fa fa-edit"></i> ویرایش
                                            </a>
                                            @if (!item.IsRemoved)
                                            {
                                                <a asp-controller="ProductPicture" asp-action="Remove" asp-route-id="@item.Id"
                                           class="btn btn-danger waves-effect waves-light m-b-5">حذف</a>
                                            }
                                            else
                                            {
                                                <a asp-controller="ProductPicture" asp-action="Restore" asp-route-id="@item.Id"
                                           class="btn btn-success waves-effect waves-light m-b-5">بازیابی</a>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#datatable').dataTable();
        });
    </script>
}